require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '11.0'

target 'cptr' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    # to enable hermes on ios, change this to true and install pods
    :hermes_enabled => false
  )

  target 'cptrTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!()

  post_install do |installer|
    react_native_post_install(installer)
  end
end

target 'cptr-tvOS' do
  # Pods for cptr-tvOS

  target 'cptr-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
