projects:
  cptr:
    schemaPath: amplify/backend/api/cptr/build/schema.graphql
    includes:
      - app/graphql/**/*.ts
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: typescript
        generatedFileName: src/API.ts
        docsFilePath: app/graphql
        region: us-east-1
        apiId: null
extensions:
  amplify:
    version: 3
